import "./globals.css";
import type { Metadata } from "next";
import { Inter, Josefin_Sans, Nova_Square } from "next/font/google";
import UserProvider from "@/context/userContext";
import TodoProvider from "@/context/todoContext";

const inter = Inter({ subsets: ["latin"] });
const Josefin = Josefin_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <TodoProvider>
          <body className={Josefin.className}>{children}</body>
        </TodoProvider>
      </UserProvider>
    </html>
  );
}
